version: '3.1'

services:
  mongo:
    image: mongo
    restart: always

    # volumes:
    #   - ./db:/data/db
    #   - ./configdb:/data/configdb
  kyukoubot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .envrc
    ports:
      - $PORT:8080
    volumes:
      - ./:/wd-kyukou-bot