url_prefix: https://dev.shosato.jp
mongo_url: 'mongodb://localhost:8070/'
port: 5426

line:
  __ENV__access_token: KYUKOU_LINE_ACCESS_TOKEN
  __ENV__channel_secret: KYUKOU_LINE_CHANNEL_SECRET
  channel_id: 1622536568

line_notify:
  client_id: UC00AINvR0Jtm3mThDVZPS
  __ENV__client_secret: KYUKOU_LINE_NOTIFY_client_SECRET
  redirect_uri: /api/v1/line/notify

twitter:
  callback_path: /api/v1/twitter/callback

email:
  __ENV__password: KYUKOU_LINE_CHANNEL_SECRET
  smtp_server: yellowcoyote4.sakura.ne.jp
  smtp_port: 587
  from_addr: kyukou@shosato.jp
  
google:
  __ENV__google_client_secret: KYUKOU_GOOGLE_CLIENT_SECRET

public_dir: ./web/public
index: index.html


__ENV__hash_salt: KYUKOU_HASH_SALT
logfile: /home/sho/repos/wd-kyukou-bot/log.txt
log_level: 1